/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BilibiliBangumi {
        "api": string;
    }
}
declare global {
    interface HTMLBilibiliBangumiElement extends Components.BilibiliBangumi, HTMLStencilElement {
    }
    var HTMLBilibiliBangumiElement: {
        prototype: HTMLBilibiliBangumiElement;
        new (): HTMLBilibiliBangumiElement;
    };
    interface HTMLElementTagNameMap {
        "bilibili-bangumi": HTMLBilibiliBangumiElement;
    }
}
declare namespace LocalJSX {
    interface BilibiliBangumi {
        "api"?: string;
    }
    interface IntrinsicElements {
        "bilibili-bangumi": BilibiliBangumi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bilibili-bangumi": LocalJSX.BilibiliBangumi & JSXBase.HTMLAttributes<HTMLBilibiliBangumiElement>;
        }
    }
}
